name: Render RMarkdown

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown", "ggplot2", "dplyr"))'

      - name: Render RMarkdown
        run: |
          R -e 'rmarkdown::render("EDA_ML_on_BreastCancer.Rmd")'
      
      - name: Upload HTML output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rendered-html
          path: EDA_ML_on_BreastCancer.html