name: Render RMarkdown

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This grants write access to the repository

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown", "ggplot2", "dplyr"))'

      - name: Render RMarkdown
        run: |
          R -e 'rmarkdown::render("EDA_ML_on_BreastCancer.Rmd")'

      - name: Commit and push to GitHub Pages branch
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git checkout -b gh-pages
          git add EDA_ML_on_BreastCancer.html
          git commit -m "Publish rendered HTML to GitHub Pages"
          git push origin gh-pages --force
